# Site settings
title: Panagiotis Stylianos
description: This is my Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: PanosStil
user_description: I'm a Data Analyst from Greece, always searching for the next challenge; no task is too scary nor too difficult. 
email: panagiotisstilianos23@gmail.com
# twitter_username: lorem_ipsum
instagram_username: Panos_Stil
facebook_username: Panos Stil
linkedin_username: https://www.linkedin.com/in/panagiotis-stylianos-5a909a1b1/
github_username:  PanosStil
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

